/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppConfigDialog: typeof import('./src/components/apps/AppConfigDialog.vue')['default']
    AppFilters: typeof import('./src/components/apps/AppFilters.vue')['default']
    AppList: typeof import('./src/components/apps/AppList.vue')['default']
    AppsPageSkeleton: typeof import('./src/components/apps/AppsPageSkeleton.vue')['default']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    OnlineTemplateDialog: typeof import('./src/components/OnlineTemplateDialog.vue')['default']
    TemplateCard: typeof import('./src/components/templates/TemplateCard.vue')['default']
    TemplateDialog: typeof import('./src/components/templates/TemplateDialog.vue')['default']
    TemplateHeader: typeof import('./src/components/templates/TemplateHeader.vue')['default']
    TemplateList: typeof import('./src/components/templates/TemplateList.vue')['default']
  }
}
